version: '2.1'
services:
# Nginx proxy server. It will serve static files and redirect all other
# requests to the Django Codeschool application. Both containers communicate
# using a TCP connection on port 8000.
    nginx:
        image: nginx:1.11
        container_name: nginx_proxy
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./src/produtos_ivone/static/media/:/var/www/static/media/
            - ./src/produtos_ivone/static/:/var/www/static/
            - ./docker/sock/:/tmp/sock/
        depends_on:
            - web
        ports:
            - '80:80'
    webapp:
        image: "produtos_ivone"
        build: .
        container_name: produtos_ivone-app
        volumes:
            - ./src/:/code/src/
            - ./nginx/:/docker/conf.d
            - ./docker/sock/:/tmp/sock/
          code LANG=C.UTF-8
        depends_on:
          - db
        expose:
          - "80"
        command: bash -c "inv deploy"
    db:
        image: postgres:latest
        container_name: db